/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import juego.Conexion;

/**
 *
 * @author pinha
 */
public class Base_Datos extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs;
    
    JLabel aux = new JLabel();

    
    

    public Base_Datos() {
        this.setLocationRelativeTo(null);   
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitulo = new JLabel();
        jLabel1 = new JLabel();
        lNombre = new JLabel();
        jLabel3 = new JLabel();
        lObjetivo = new JLabel();
        jLabel4 = new JLabel();
        lMonstruos = new JLabel();
        jLabel5 = new JLabel();
        lCumplio = new JLabel();
        bConsultar = new javax.swing.JToggleButton();
        bVolver = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        lTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(0, 51, 51));
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("REGISTRO");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOMBRE DEL JUGADOR");

        lNombre.setBackground(new java.awt.Color(0, 153, 153));
        lNombre.setBorder(new javax.swing.border.MatteBorder(null));
        lNombre.setOpaque(true);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("OBJETIVO DEL JUGADOR");

        lObjetivo.setBackground(new java.awt.Color(0, 153, 153));
        lObjetivo.setBorder(new javax.swing.border.MatteBorder(null));
        lObjetivo.setOpaque(true);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("MONSTRUOS DERROTADOS");

        lMonstruos.setBackground(new java.awt.Color(0, 153, 153));
        lMonstruos.setBorder(new javax.swing.border.MatteBorder(null));
        lMonstruos.setOpaque(true);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CUMPLIO CON SU OBJETIVO");

        lCumplio.setBackground(new java.awt.Color(0, 153, 153));
        lCumplio.setBorder(new javax.swing.border.MatteBorder(null));
        lCumplio.setOpaque(true);

        bConsultar.setBackground(new java.awt.Color(0, 102, 102));
        bConsultar.setForeground(new java.awt.Color(255, 255, 255));
        bConsultar.setText("CONSULTAR");
        bConsultar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 51, 51)));
        bConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarActionPerformed(evt);
            }
        });

        bVolver.setBackground(new java.awt.Color(102, 255, 204));
        bVolver.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        bVolver.setForeground(new java.awt.Color(0, 0, 204));
        bVolver.setText("X");
        bVolver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 204), 1, true));
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCumplio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lMonstruos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(bConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bVolver)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMonstruos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lCumplio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarActionPerformed

        

        try {

            Connection con = Conexion.instance.establecerConexion();
            String nombre = JOptionPane.showInputDialog("ESCRIBE EL NOMBRE DEL JUGADOR DEL QUE DESEAS CONSULTAR LOS DATOS");

            ps = (PreparedStatement) con.prepareStatement("SELECT * FROM partidas WHERE NombreJugador = ?");
            ps.setString(1, nombre);

            rs = ps.executeQuery();
            JOptionPane.showMessageDialog(null, "CONSULTA REALIZADA CON EXITO");
            if (rs.next()) {
                lNombre.setText(rs.getString("NombreJugador"));
                lObjetivo.setText(rs.getString("Objetivo"));
                lMonstruos.setText(rs.getString("Monstruos"));
                lCumplio.setText(rs.getString("ObjetivoConseguido"));
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_bConsultarActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        setVisible(false);
        Interfaz.jugador.chequeo(Interfaz.jugador, Interfaz.monster, aux, Interfaz.fich);
    }//GEN-LAST:event_bVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Base_Datos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bConsultar;
    private javax.swing.JToggleButton bVolver;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private JLabel lCumplio;
    private JLabel lMonstruos;
    private JLabel lNombre;
    private JLabel lObjetivo;
    private JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
